# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pokeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pokeApp
  pod 'Alamofire'
  pod 'RxCocoa'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'MBProgressHUD'
  pod 'netfox'
  pod 'SnapKit'
  pod 'XLPagerTabStrip'

  target 'pokeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pokeAppUITests' do
    # Pods for testing
  end

end
